<h2>All Users</h2>
<a href="user/add"><button class="btn btn-default btn-primary">Add New</button></a>
<table class="table">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($this->personList as $person) {?>
    <tr>
      <td><?php echo $person->getFirstName(); ?></td>
      <td><?php echo $person->getLastName(); ?></td>
      <td><?php echo $person->getEmail(); ?></td>
    </tr>
    <?php } ?>
  </tbody>
</table>